### ISSUE TITLE
Fixes needed for swarm demo dapps

### ISSUE THREAD

**Issue by homotopycolimit** [ethersphere/swarm-team-issues#1]
We have a bunch of demo apps deployed on swarm (overview at swarmdapps.eth). They come mostly form this repo: https://github.com/ethereum/swarm-dapps

We have a number of small issues that need to be fixed
- [x] Enable empty **photoalbum** (currently one must delete all-but-one image, upload a new one, delete the last remaining old one.
- [x] reverse file order when uploading to **photoalbum** (currently when uploading multiple images, their order is reversed)
- [x] when deleting images from **photoalbum**, they should be removed from the manifest
- [x] have default markdown document for the **markdown-editor** (currently when we call up the editor directly, we just get an error)
- [x] fix **filemanager** to show pop-up file selector in all browsers (currently many browsers just get stuck in a loading animation)

**Comment by homotopycolimit** [comment]
See also:
https://github.com/ethereum/swarm-dapps/issues/11
https://github.com/ethereum/swarm-dapps/issues/10
https://github.com/ethereum/swarm-dapps/issues/9
https://github.com/ethereum/swarm-dapps/issues/8
https://github.com/ethereum/swarm-dapps/issues/14

**Comment by homotopycolimit** [comment]
Updates that would be nice on these dapps:

- [ ] a "save' button on the markdown editor that saves the current version of the markdown document to an ENS name.

**Comment by homotopycolimit** [comment]
@nagydani, could you comment on these issues? I feel like you have the best overview to be able to say what it takes to address them.

**Comment by nagydani** [comment]
Sorry for not answering, temporarily lost access to my GitHub account. Most of them are at most a few days worth of work, already started doing them with @IgorShadurin 
See https://github.com/ethereum/swarm-dapps/pull/16
